### ISSUE TITLE
Media not playing in KitKat

### ISSUE THREAD

**Issue by AbhijithMadhav** [AbhijithMadhav/yo-yo#13]
`01-08 12:54:02.517 3287-3287/com.am.yo_yo E/MediaPlayer: Should have subtitle controller already set`

**Comment by abhimaanmadhav** [comment]
is this still valid??

**Comment by AbhijithMadhav** [comment]
Yup

**Comment by abhimaanmadhav** [comment]
tested on 4.4 in emulator it is playing beep as well as countdown sound

**Comment by abhimaanmadhav** [comment]
@AbhijithMadhav pls verify and close it??
