### ISSUE TITLE
Multiple timer created

### ISSUE THREAD

**Issue by abhimaanmadhav** [AbhijithMadhav/yo-yo#16]
Timer should only be created once in activity lifecycle. If The user minimise the app N number of time N timer is created.

**Comment by abhimaanmadhav** [comment]
you can also bind the service one in activity life cycle

**Comment by AbhijithMadhav** [comment]
@abhimaanmadhav 

> Timer should only be created once in activity lifecycle. If The user minimise the app N number of time N timer is created.

That shouldn't be a problem right? I want to cancel the timer everytime the `onStop` is called(https://github.com/AbhijithMadhav/yo-yo/issues/14). Once I call cancel, the timer object is as good as dead(https://docs.oracle.com/javase/7/docs/api/java/util/Timer.html#cancel()) and I can't schedule on it anymore when the `onStart` is called again.

**Comment by AbhijithMadhav** [comment]
@abhimaanmadhav 

> you can also bind the service one in activity life cycle

You mean bind and unbind in `onCreate` and `onDestroy`?

> If you need to interact with the service only while your activity is visible, you should bind during onStart() and unbind during onStop()

https://developer.android.com/guide/components/bound-services.html#Additional_Notes

**Comment by abhimaanmadhav** [comment]
@AbhijithMadhav would like to discuss more about whether should the timer be started and cancel every onstart and onstop

**Comment by abhimaanmadhav** [comment]
@AbhijithMadhav agree with bind and unbind thing
