### ISSUE TITLE
setting activity does not go back to home

### ISSUE THREAD

**Issue by abhimaanmadhav** [AbhijithMadhav/yo-yo#18]
Go to settings activity-> press recent button/home button -> then open apps from recents->press back it quits the app.

cc @AbhijithMadhav

**Comment by AbhijithMadhav** [comment]
RC required andre yannappa?

**Comment by abhimaanmadhav** [comment]
means "root cause" analysis required

**Comment by AbhijithMadhav** [comment]
https://developer.android.com/training/implementing-navigation/ancestral.html

@abhimaanmadhav 
I'm thinking that when the app was minimized the parent was no longer the home activity. Not sure
